[package]
name = "lake"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"

[dependencies]
tree-sitter = "^0.20.10"

[build-dependencies]
cc = "^1.0"
tree-sitter-cli = "^0.20.8"
walkdir = "^2"
