[package]
name = "lake"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"

[dependencies]
rmp-serde = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
tree-sitter = "0.20.10"
tree-sitter-lake = { path = "tree-sitter-lake" }
